### ISSUE TITLE
`nvm run watch` Fails

### ISSUE THREAD

**Issue by mikebronner** [variejs/varie#11]
It appears that running `nvm run watch` fails in my environment:
```sh
npm run watch

> @ watch /Users/mike/Developer/Sites/xxxx
> webpack-dev-server --mode development --hot

clean-webpack-plugin: /Users/mike/Developer/Sites/xxxx/public has been removed.
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND varie.test
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1495:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `webpack-dev-server --mode development --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mike/.npm/_logs/2018-07-04T01_48_38_409Z-debug.log
```

The work-around for me has been to add the localhost IP address to the watch command in `packages.json`:
```json
    "watch": "webpack-dev-server --mode development --hot --host 127.0.0.1",
```

**Comment by lukepolo** [comment]
Curious if you changed the varie.test to localhost it would have worked, know you changed that in the other issue , I’d day try removing the —host now and bet it works

**Comment by mikebronner** [comment]
Your right! Fixing the config setting worked. #12 I reverted this back to not have the `--host` parameter.
